In [1]:
import pandas as pd
#Loading dataset
df=pd.read_csv('SuperStore_EDA_v1.csv')

# Intial Exloration of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10014 entries, 0 to 10013
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10014 non-null  int64
 1   Order ID       10014 non-null  object
 2   Order Date     10014 non-null  object
 3   Ship Date      10014 non-null  object
 4   Ship Mode      9916 non-null   object
 5   Customer ID    10014 non-null  object
 6   Customer Name  10014 non-null  object
 7   Segment        10014 non-null  object
 8   Country        10014 non-null  object
 9   City           10014 non-null  object
 10  State          10014 non-null  object
 11  Postal Code    10014 non-null  int64
 12  Region         10014 non-null  object
 13  Product ID     10014 non-null  object
 14  Category       10014 non-null  object
 15  Sub-Category   10014 non-null  object
 16  Product Name   10014 non-null  object
 17  Sales Price    10014 non-null  float64
 18  Quantity       9996 non-null   float64
 19  Discount       10014 non-null  float64
 20  Profit         10014 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,12/06/16,16/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [3]:
df.shape

(10014, 21)

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales Price', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
#Data Types
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales Price      float64
Quantity         float64
Discount         float64
Profit           float64
dtype: object

In [6]:
#Summary Statistics
df.describe()

,Row ID,Postal Code,Sales Price,Quantity,Discount,Profit
count,10014.000000,10014.000000,10014.000000,9996.000000,10014.000000,10014.000000
mean,4997.523367,55205.131616,230.038424,3.792517,0.156240,28.708317
std,2888.981754,32066.711027,623.057359,2.231021,0.206392,234.154272
min,1.000000,1040.000000,-31.500000,1.000000,0.000000,-6599.978000
25%,2494.250000,23223.000000,17.280000,2.000000,0.000000,1.731375
50%,4997.500000,57103.000000,54.780000,3.000000,0.200000,8.666500
75%,7500.750000,90008.000000,209.970000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [7]:
#Summary Statistics
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
count,10014.000000,10014,10014,10014,9916,10014,10014,10014,10014,10014,...,10014.000000,10014,10014,10014,10014,10014,10014.000000,9996.000000,10014.000000,10014.000000
unique,NaN,5009,1240,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,05/09/16,16/12/15,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5908,37,37,5203,10014,917,...,NaN,3212,19,6037,1526,48,NaN,NaN,NaN,NaN
mean,4997.523367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55205.131616,NaN,NaN,NaN,NaN,NaN,230.038424,3.792517,0.156240,28.708317
std,2888.981754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32066.711027,NaN,NaN,NaN,NaN,NaN,623.057359,2.231021,0.206392,234.154272
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,-31.500000,1.000000,0.000000,-6599.978000
25%,2494.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.731375
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57103.000000,NaN,NaN,NaN,NaN,NaN,54.780000,3.000000,0.200000,8.666500
75%,7500.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.970000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [8]:
#Unique Values Count
df.nunique()

Row ID           9994
Order ID         5009
Order Date       1240
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              54
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1850
Sales Price      5829
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [9]:
#Missing or discrepancies Values
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode        98
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales Price       0
Quantity         18
Discount          0
Profit            0
dtype: int64

**IDENTIFY DATA QUALITY ISSUES**

In [10]:
#Dropping duplicates
rows_before=len(df)
orderids_before=df['Order ID'].nunique()

df=df.drop_duplicates()

rows_after=len(df)
orderids_after=df['Order ID'].nunique()
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,12/06/16,16/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,26/02/17,03/03/17,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994,CA-2017-119914,04/05/17,09/05/17,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480
9998,20,CA-2014-143336,27/08/14,2014-9-1,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110
10000,8852,CA-2015-140718,02/07/15,04/07/15,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,27604,South,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872
10005,1044,CA-2017-115651,09/07/17,12/07/17,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,60610,Central,OFF-AR-10001130,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835

In [11]:
#Data Exploration after dropping duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9997 non-null   int64
 1   Order ID       9997 non-null   object
 2   Order Date     9997 non-null   object
 3   Ship Date      9997 non-null   object
 4   Ship Mode      9899 non-null   object
 5   Customer ID    9997 non-null   object
 6   Customer Name  9997 non-null   object
 7   Segment        9997 non-null   object
 8   Country        9997 non-null   object
 9   City           9997 non-null   object
 10  State          9997 non-null   object
 11  Postal Code    9997 non-null   int64
 12  Region         9997 non-null   object
 13  Product ID     9997 non-null   object
 14  Category       9997 non-null   object
 15  Sub-Category   9997 non-null   object
 16  Product Name   9997 non-null   object
 17  Sales Price    9997 non-null   float64
 18  Quantity       9979 non-null   float64
 19  Discount       9997 non-null   float64
 20  Profit         9997 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.7+ MB

In [12]:
#Data Affected
print("Duplicate Removal Report")
print(f"Intital Rows:{rows_before}   After Removal: {rows_after}")
print(f"Intital Distinct OrderIds:{orderids_before}   After Removal: {orderids_after}")

Duplicate Removal Report
Intital Rows:10014   After Removal: 9997
Intital Distinct OrderIds:5009   After Removal: 5009

***DATA HANDLING***

In [13]:
#Before Data Handling Rows and OrderIds
rows_before=len(df)
orderids_before=df['Order ID'].nunique()

In [14]:
#Normalizing Order Data and Ship Date
df['Order Date']=pd.to_datetime(df['Order Date'], format='%d/%m/%y', errors='coerce')
df['Ship Date']=pd.to_datetime(df['Ship Date'],  format='%d/%m/%y',errors='coerce')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480
9998,20,CA-2014-143336,2014-08-27,NaT,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,27604,South,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,60610,Central,OFF-AR-10001130,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9997 non-null   int64
 1   Order ID       9997 non-null   object
 2   Order Date     9997 non-null   datetime64[ns]
 3   Ship Date      8056 non-null   datetime64[ns]
 4   Ship Mode      9899 non-null   object
 5   Customer ID    9997 non-null   object
 6   Customer Name  9997 non-null   object
 7   Segment        9997 non-null   object
 8   Country        9997 non-null   object
 9   City           9997 non-null   object
 10  State          9997 non-null   object
 11  Postal Code    9997 non-null   int64
 12  Region         9997 non-null   object
 13  Product ID     9997 non-null   object
 14  Category       9997 non-null   object
 15  Sub-Category   9997 non-null   object
 16  Product Name   9997 non-null   object
 17  Sales Price    9997 non-null   float64
 18  Quantity       9979 non-null   float64
 19  Discount       9997 non-null   float64
 20  Profit         9997 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.7+ MB

In [16]:
df['Ship Date']=df['Ship Date'].fillna(df['Order Date'])
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,27604,South,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,60610,Central,OFF-AR-10001130,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9997 non-null   int64
 1   Order ID       9997 non-null   object
 2   Order Date     9997 non-null   datetime64[ns]
 3   Ship Date      9997 non-null   datetime64[ns]
 4   Ship Mode      9899 non-null   object
 5   Customer ID    9997 non-null   object
 6   Customer Name  9997 non-null   object
 7   Segment        9997 non-null   object
 8   Country        9997 non-null   object
 9   City           9997 non-null   object
 10  State          9997 non-null   object
 11  Postal Code    9997 non-null   int64
 12  Region         9997 non-null   object
 13  Product ID     9997 non-null   object
 14  Category       9997 non-null   object
 15  Sub-Category   9997 non-null   object
 16  Product Name   9997 non-null   object
 17  Sales Price    9997 non-null   float64
 18  Quantity       9979 non-null   float64
 19  Discount       9997 non-null   float64
 20  Profit         9997 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.7+ MB

In [18]:
df['OrderID Year']=df['Order ID'].apply(lambda x: int(x.split('-')[1]))
df['OrderDate Year']=df['Order Date'].dt.year
year_inconsistences=df[df['OrderID Year'] !=df['OrderDate Year']]
year_inconsistences

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year
62,63,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,TEC-AC-10004633,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,13.980,2.0,0.0,6.1512,2015,2017
63,64,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-BI-10001078,Office Supplies,Binders,"Acco PRESSTEX Data Binder with Storage Hooks, ...",25.824,6.0,0.2,9.3612,2015,2017
64,65,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-PA-10003892,Office Supplies,Paper,Xerox 1943,146.730,3.0,0.0,68.9631,2015,2017
65,66,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,FUR-FU-10000397,Furniture,Furnishings,Luxo Economy Swing Arm Lamp,79.760,4.0,0.0,22.3328,2015,2017
943,944,CA-2015-120880,2013-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,32.400,5.0,0.0,15.5520,2015,2013
944,945,CA-2015-120880,2013-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-ST-10001496,Office Supplies,Storage,Standard Rollaway File with Lock,540.570,3.0,0.0,140.5482,2015,2013
945,946,CA-2015-120880,2013-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-BI-10002931,Office Supplies,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",167.760,5.0,0.2,62.9100,2015,2013
1152,1153,CA-2017-160395,2016-12-31,2017-01-06,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-AR-10003759,Office Supplies,Art,"Crayola Anti Dust Chalk, 12/Pack",3.640,2.0,0.0,1.6380,2017,2016
1153,1154,CA-2017-160395,2016-12-31,2017-01-06,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-BI-10003984,Office Supplies,Binders,Lock-Up Easel 'Spel-Binder',159.768,7.0,0.2,53.9217,2017,2016
2752,2753,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AR-10003251,Office Supplies,Art,Prang Drawing Pencil Set,5.560,2.0,0.0,2.2240,2015,1999
2753,2754,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,323.370,3.0,0.0,129.3480,2015,1999
2754,2755,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-PH-10002310,Technology,Phones,Plantronics Calisto P620-M USB Wireless Speake...,783.960,5.0,0.2,68.5965,2015,1999
2755,2756,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AP-10002651,Office Supplies,Appliances,Hoover Upright Vacuum With Dirt Cup,1447.650,5.0,0.0,419.8185,2015,1999
2756,2757,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-PA-10001184,Office Supplies,Paper,Xerox 1903,11.960,2.0,0.0,5.8604,2015,1999
2821,2822,CA-2017-100202,2016-12-31,2017-01-05,Standard Class,BD-11620,Brian DeCherney,Consumer,United States,Anaheim,...,TEC-PH-10002563,Technology,Phones,Adtran 1202752G1,302.376,3.0,0.2,22.6782,2017,2016
3537,3538,CA-2014-158771,2015-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3.0,0.0,14.9850,2014,2015
3538,3539,CA-2014-158771,2015-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3.0,0.0,4.5360,2014,2015
3539,3540,CA-2014-158771,2015-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10003121,Office Supplies,Labels,Avery 506,20.650,5.0,0.0,9.4990,2014,2015
3540,3541,CA-2014-158771,2015-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7.0,0.0,21.7728,2014,2015
4448,4449,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,FUR-FU-10000732,Furniture,Furnishings,Eldon 200 Class Desk Accessories,12.560,2.0,0.0,4.0192,2015,2017
4449,4450,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-PA-10004355,Office Supplies,Paper,Xerox 231,6.480,1.0,0.0,3.1104,2015,2017
4450,4451,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,186.690,3.0,0.0,87.7443,2015,2017
4612,4613,US-2017-165953,2016-12-31,2017-01-06,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-AR-10000588,Office Supplies,Art,Newell 345,47.616,3.0,0.2,3.5712,2017,2016
4613,4614,US-2017-165953,2016-12-31,2017-01-06,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,23.480,5.0,0.2,8.2180,2017,2016
5289,5290,CA-2014-146283,2016-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10002259,Office Supplies,Paper,"Geographics Note Cards, Blank, White, 8 1/2"" x...",17.904,2.0,0.2,6.2664,2014,2016
5290,5291,CA-2014-146283,2016-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,966.700,5.0,0.3,-13.8100,2014,2016
5291,5292,CA-2014-146283,2016-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10000482,Office Supplies,Paper,Snap-A-Way Black Print Carbonless Ruled Speed ...,182.112,6.0,0.2,61.4628,2014,2016
5372,5373,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10003177,Office Supplies,Paper,Xerox 1999,15.552,3.0,0.2,5.4432,2015,2014
5373,5374,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,FUR-TA-10002607,Furniture,Tables,KI Conference Tables,347.361,7.0,0.3,-69.4722,2015,2014
5374,5375,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10001166,Office Supplies,Paper,Xerox 2,10.368,2.0,0.2,3.6288,2015,2014
5738,5739,CA-2017-156139,2016-12-31,2017-01-06,Standard Class,BP-11155,Becky Pak,Consumer,United States,San Francisco,...,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",38.376,3.0,0.2,13.4316,2017,2016
6341,6342,US-2017-105830,2016-12-31,2017-01-02,First Class,DB-13660,Duane Benoit,Consumer,United States,Lancaster,...,OFF-ST-10002554,Office Supplies,Storage,Tennsco Industrial Shelving,156.512,4.0,0.2,-35.2152,2017,2016
6387,6388,CA-2014-134103,2017-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-PA-10001204,Office Supplies,Paper,Xerox 1972,10.560,2.0,0.0,4.7520,2014,2017
6388,6389,CA-2014-134103,2017-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-ST-10000991,Office Supplies,Storage,Space Solutions HD Industrial Steel Shelving.,229.940,2.0,0.0,6.8982,2014,2017
8586,8587,CA-2017-162015,2015-07-11,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,TEC-AC-10003832,Technology,Accessories,Logitech�P710e Mobile Speakerphone,1287.450,5.0,0.0,244.6155,2017,2015
8587,8588,CA-2017-162015,2015-07-11,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,OFF-AP-10003040,Office Supplies,Appliances,Fellowes 8 Outlet Superior Workstation Surge P...,168.100,5.0,0.0,43.7060,2017,2015
8595,8596,CA-2014-111934,2029-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-BI-10004364,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2.0,0.0,5.3460,2014,2029
8596,8597,CA-2014-111934,2029-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,35.440,1.0,0.0,16.6568,2014,2029
9942,9943,CA-2014-143371,2019-12-28,2015-01-03,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.820,9.0,0.0,29.9646,2014,2019
9943,9944,CA-2014-143371,2019-12-28,2015-01-03,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-SU-10002537,Office Supplies,Supplies,Acme Box Cutter Scissors,51.150,5.0,0.0,13.2990,2014,2019

In [19]:
idx=year_inconsistences.index
idx

Index([  62,   63,   64,   65,  943,  944,  945, 1152, 1153, 2752, 2753, 2754,
       2755, 2756, 2821, 3537, 3538, 3539, 3540, 4448, 4449, 4450, 4612, 4613,
       5289, 5290, 5291, 5372, 5373, 5374, 5738, 6341, 6387, 6388, 8586, 8587,
       8595, 8596, 9942, 9943],
      dtype='int64')

In [20]:
year_inconsistences.shape

(40, 23)

In [21]:
df.loc[idx,'Order Date']=pd.to_datetime(
    df.loc[idx,'OrderID Year'].astype(str) +'-'+
    df.loc[idx,'Order Date'].dt.month.astype(str) +'-'+
    df.loc[idx,'Order Date'].dt.day.astype(str)
)
rows_impacted=year_inconsistences.shape[0]
orderids_impacted=year_inconsistences['Order ID'].nunique()
print(f"Rows impacted by date handling: {rows_impacted}")
print(f"Order IDs impacted:{orderids_impacted}")

Rows impacted by date handling: 40
Order IDs impacted:16

In [22]:
df.loc[idx]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year
62,63,CA-2015-135545,2015-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,TEC-AC-10004633,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,13.980,2.0,0.0,6.1512,2015,2017
63,64,CA-2015-135545,2015-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-BI-10001078,Office Supplies,Binders,"Acco PRESSTEX Data Binder with Storage Hooks, ...",25.824,6.0,0.2,9.3612,2015,2017
64,65,CA-2015-135545,2015-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-PA-10003892,Office Supplies,Paper,Xerox 1943,146.730,3.0,0.0,68.9631,2015,2017
65,66,CA-2015-135545,2015-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,FUR-FU-10000397,Furniture,Furnishings,Luxo Economy Swing Arm Lamp,79.760,4.0,0.0,22.3328,2015,2017
943,944,CA-2015-120880,2015-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,32.400,5.0,0.0,15.5520,2015,2013
944,945,CA-2015-120880,2015-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-ST-10001496,Office Supplies,Storage,Standard Rollaway File with Lock,540.570,3.0,0.0,140.5482,2015,2013
945,946,CA-2015-120880,2015-05-29,2015-06-03,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-BI-10002931,Office Supplies,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",167.760,5.0,0.2,62.9100,2015,2013
1152,1153,CA-2017-160395,2017-12-31,2017-01-06,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-AR-10003759,Office Supplies,Art,"Crayola Anti Dust Chalk, 12/Pack",3.640,2.0,0.0,1.6380,2017,2016
1153,1154,CA-2017-160395,2017-12-31,2017-01-06,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-BI-10003984,Office Supplies,Binders,Lock-Up Easel 'Spel-Binder',159.768,7.0,0.2,53.9217,2017,2016
2752,2753,CA-2015-155306,2015-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AR-10003251,Office Supplies,Art,Prang Drawing Pencil Set,5.560,2.0,0.0,2.2240,2015,1999
2753,2754,CA-2015-155306,2015-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,323.370,3.0,0.0,129.3480,2015,1999
2754,2755,CA-2015-155306,2015-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-PH-10002310,Technology,Phones,Plantronics Calisto P620-M USB Wireless Speake...,783.960,5.0,0.2,68.5965,2015,1999
2755,2756,CA-2015-155306,2015-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AP-10002651,Office Supplies,Appliances,Hoover Upright Vacuum With Dirt Cup,1447.650,5.0,0.0,419.8185,2015,1999
2756,2757,CA-2015-155306,2015-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-PA-10001184,Office Supplies,Paper,Xerox 1903,11.960,2.0,0.0,5.8604,2015,1999
2821,2822,CA-2017-100202,2017-12-31,2017-01-05,Standard Class,BD-11620,Brian DeCherney,Consumer,United States,Anaheim,...,TEC-PH-10002563,Technology,Phones,Adtran 1202752G1,302.376,3.0,0.2,22.6782,2017,2016
3537,3538,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3.0,0.0,14.9850,2014,2015
3538,3539,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3.0,0.0,4.5360,2014,2015
3539,3540,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10003121,Office Supplies,Labels,Avery 506,20.650,5.0,0.0,9.4990,2014,2015
3540,3541,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7.0,0.0,21.7728,2014,2015
4448,4449,CA-2015-121965,2015-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,FUR-FU-10000732,Furniture,Furnishings,Eldon 200 Class Desk Accessories,12.560,2.0,0.0,4.0192,2015,2017
4449,4450,CA-2015-121965,2015-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-PA-10004355,Office Supplies,Paper,Xerox 231,6.480,1.0,0.0,3.1104,2015,2017
4450,4451,CA-2015-121965,2015-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,186.690,3.0,0.0,87.7443,2015,2017
4612,4613,US-2017-165953,2017-12-31,2017-01-06,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-AR-10000588,Office Supplies,Art,Newell 345,47.616,3.0,0.2,3.5712,2017,2016
4613,4614,US-2017-165953,2017-12-31,2017-01-06,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,23.480,5.0,0.2,8.2180,2017,2016
5289,5290,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10002259,Office Supplies,Paper,"Geographics Note Cards, Blank, White, 8 1/2"" x...",17.904,2.0,0.2,6.2664,2014,2016
5290,5291,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,966.700,5.0,0.3,-13.8100,2014,2016
5291,5292,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10000482,Office Supplies,Paper,Snap-A-Way Black Print Carbonless Ruled Speed ...,182.112,6.0,0.2,61.4628,2014,2016
5372,5373,CA-2015-118738,2015-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10003177,Office Supplies,Paper,Xerox 1999,15.552,3.0,0.2,5.4432,2015,2014
5373,5374,CA-2015-118738,2015-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,FUR-TA-10002607,Furniture,Tables,KI Conference Tables,347.361,7.0,0.3,-69.4722,2015,2014
5374,5375,CA-2015-118738,2015-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10001166,Office Supplies,Paper,Xerox 2,10.368,2.0,0.2,3.6288,2015,2014
5738,5739,CA-2017-156139,2017-12-31,2017-01-06,Standard Class,BP-11155,Becky Pak,Consumer,United States,San Francisco,...,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",38.376,3.0,0.2,13.4316,2017,2016
6341,6342,US-2017-105830,2017-12-31,2017-01-02,First Class,DB-13660,Duane Benoit,Consumer,United States,Lancaster,...,OFF-ST-10002554,Office Supplies,Storage,Tennsco Industrial Shelving,156.512,4.0,0.2,-35.2152,2017,2016
6387,6388,CA-2014-134103,2014-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-PA-10001204,Office Supplies,Paper,Xerox 1972,10.560,2.0,0.0,4.7520,2014,2017
6388,6389,CA-2014-134103,2014-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-ST-10000991,Office Supplies,Storage,Space Solutions HD Industrial Steel Shelving.,229.940,2.0,0.0,6.8982,2014,2017
8586,8587,CA-2017-162015,2017-07-11,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,TEC-AC-10003832,Technology,Accessories,Logitech�P710e Mobile Speakerphone,1287.450,5.0,0.0,244.6155,2017,2015
8587,8588,CA-2017-162015,2017-07-11,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,OFF-AP-10003040,Office Supplies,Appliances,Fellowes 8 Outlet Superior Workstation Surge P...,168.100,5.0,0.0,43.7060,2017,2015
8595,8596,CA-2014-111934,2014-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-BI-10004364,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2.0,0.0,5.3460,2014,2029
8596,8597,CA-2014-111934,2014-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,35.440,1.0,0.0,16.6568,2014,2029
9942,9943,CA-2014-143371,2014-12-28,2015-01-03,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.820,9.0,0.0,29.9646,2014,2019
9943,9944,CA-2014-143371,2014-12-28,2015-01-03,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-SU-10002537,Office Supplies,Supplies,Acme Box Cutter Scissors,51.150,5.0,0.0,13.2990,2014,2019

In [23]:
df['Days to Ship']=(df['Ship Date']-df['Order Date']).dt.days
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year,Days to Ship
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,2016,2016,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,2016,2016,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,2016,2016,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,2015,2015,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,2015,2015,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200,2017,2017,5
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480,2017,2017,5
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110,2014,2014,0
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872,2015,2015,2
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835,2017,2017,3

In [24]:
max_diff=df.groupby('Ship Mode')['Days to Ship'].max()
max_diff

Ship Mode
First Class       5479
Same Day           365
Second Class         5
Standard Class    1096
Name: Days to Ship, dtype: int64

In [25]:
shipdays_issue=df[df['Days to Ship']>10]
shipdays_issue

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year,Days to Ship
3537,3538,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3.0,0.0,14.9850,2014,2015,365
3538,3539,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,Office Supplies,Labels,Avery 518,9.450,3.0,0.0,4.5360,2014,2015,365
3539,3540,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,Office Supplies,Labels,Avery 506,20.650,5.0,0.0,9.4990,2014,2015,365
3540,3541,CA-2014-158771,2014-05-09,2015-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7.0,0.0,21.7728,2014,2015,365
5289,5290,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,Office Supplies,Paper,"Geographics Note Cards, Blank, White, 8 1/2"" x...",17.904,2.0,0.2,6.2664,2014,2016,731
5290,5291,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,Furniture,Chairs,SAFCO Arco Folding Chair,966.700,5.0,0.3,-13.8100,2014,2016,731
5291,5292,CA-2014-146283,2014-09-08,2016-09-08,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,Office Supplies,Paper,Snap-A-Way Black Print Carbonless Ruled Speed ...,182.112,6.0,0.2,61.4628,2014,2016,731
6387,6388,CA-2014-134103,2014-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,Office Supplies,Paper,Xerox 1972,10.560,2.0,0.0,4.7520,2014,2017,1096
6388,6389,CA-2014-134103,2014-01-30,2017-01-30,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,Office Supplies,Storage,Space Solutions HD Industrial Steel Shelving.,229.940,2.0,0.0,6.8982,2014,2017,1096
8595,8596,CA-2014-111934,2014-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2.0,0.0,5.3460,2014,2029,5479
8596,8597,CA-2014-111934,2014-05-05,2029-05-05,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,Office Supplies,Paper,Easy-staple paper,35.440,1.0,0.0,16.6568,2014,2029,5479

In [26]:
shipdays_issue.shape

(11, 24)

In [27]:
indx=shipdays_issue.index
indx

Index([3537, 3538, 3539, 3540, 5289, 5290, 5291, 6387, 6388, 8595, 8596], dtype='int64')

In [28]:
df.loc[indx, 'Ship Date'] = pd.to_datetime(
    df.loc[indx, 'Order Date'].dt.year.astype(str) + '-' +
    df.loc[indx, 'Ship Date'].dt.strftime('%m-%d')
)
df['Days to Ship'] = (df['Ship Date'] - df['Order Date']).dt.days
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year,Days to Ship
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,2016,2016,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,2016,2016,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,2016,2016,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,2015,2015,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,2015,2015,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200,2017,2017,5
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480,2017,2017,5
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110,2014,2014,0
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872,2015,2015,2
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835,2017,2017,3

In [29]:
ship_diff=df.groupby('Ship Mode')['Days to Ship'].max()
ship_diff

Ship Mode
First Class       3
Same Day          1
Second Class      5
Standard Class    7
Name: Days to Ship, dtype: int64

In [30]:
df['Ship Mode']=df.apply(
    lambda x: 'Same Day' if x['Days to Ship']==0
    else ( 'Standard Class' if x['Days to Ship'] ==7
         else x['Ship Mode']), axis=1
)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year,Days to Ship
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,2016,2016,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,2016,2016,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,2016,2016,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,2015,2015,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,2015,2015,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200,2017,2017,5
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480,2017,2017,5
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110,2014,2014,0
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872,2015,2015,2
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835,2017,2017,3

In [31]:
print(f"Ship Date after Correction impacted rows:{shipdays_issue.shape[0]}")
print(f"Distinct OrderIds impacted by ShipDate Correction:{shipdays_issue['Order ID'].nunique()}")

Ship Date after Correction impacted rows:11
Distinct OrderIds impacted by ShipDate Correction:4

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9997 non-null   int64
 1   Order ID        9997 non-null   object
 2   Order Date      9997 non-null   datetime64[ns]
 3   Ship Date       9997 non-null   datetime64[ns]
 4   Ship Mode       9997 non-null   object
 5   Customer ID     9997 non-null   object
 6   Customer Name   9997 non-null   object
 7   Segment         9997 non-null   object
 8   Country         9997 non-null   object
 9   City            9997 non-null   object
 10  State           9997 non-null   object
 11  Postal Code     9997 non-null   int64
 12  Region          9997 non-null   object
 13  Product ID      9997 non-null   object
 14  Category        9997 non-null   object
 15  Sub-Category    9997 non-null   object
 16  Product Name    9997 non-null   object
 17  Sales Price     9997 non-null   float64
 18  Quantity        9979 non-null   float64
 19  Discount        9997 non-null   float64
 20  Profit          9997 non-null   float64
 21  OrderID Year    9997 non-null   int64
 22  OrderDate Year  9997 non-null   int32
 23  Days to Ship    9997 non-null   int64
dtypes: datetime64[ns](2), float64(4), int32(1), int64(4), object(13)
memory usage: 2.1+ MB

In [33]:
x=df['Quantity'].isnull().sum()
y=df[df['Quantity'].isnull()]['Order ID'].nunique()
rows_impacted=int(x)
orderids=int(y)
print(rows_impacted)
print(orderids)

18
17

In [34]:
#Imputing missing values in Quantity Column
df['Quantity'].describe()

count    9979.000000
mean        3.790861
std         2.226648
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        14.000000
Name: Quantity, dtype: float64

In [35]:
#Since its quantity cannot be decimal and with outliers median is best practice here
df['Quantity']=df['Quantity'].fillna(df['Quantity'].median())
df['Quantity']

0        2.0
1        3.0
2        2.0
3        5.0
4        2.0
        ...
9992     4.0
9993     2.0
9998     3.0
10000    2.0
10005    5.0
Name: Quantity, Length: 9997, dtype: float64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9997 non-null   int64
 1   Order ID        9997 non-null   object
 2   Order Date      9997 non-null   datetime64[ns]
 3   Ship Date       9997 non-null   datetime64[ns]
 4   Ship Mode       9997 non-null   object
 5   Customer ID     9997 non-null   object
 6   Customer Name   9997 non-null   object
 7   Segment         9997 non-null   object
 8   Country         9997 non-null   object
 9   City            9997 non-null   object
 10  State           9997 non-null   object
 11  Postal Code     9997 non-null   int64
 12  Region          9997 non-null   object
 13  Product ID      9997 non-null   object
 14  Category        9997 non-null   object
 15  Sub-Category    9997 non-null   object
 16  Product Name    9997 non-null   object
 17  Sales Price     9997 non-null   float64
 18  Quantity        9997 non-null   float64
 19  Discount        9997 non-null   float64
 20  Profit          9997 non-null   float64
 21  OrderID Year    9997 non-null   int64
 22  OrderDate Year  9997 non-null   int32
 23  Days to Ship    9997 non-null   int64
dtypes: datetime64[ns](2), float64(4), int32(1), int64(4), object(13)
memory usage: 2.1+ MB

In [37]:
print(f"Rows impacted by Quantity Missing Values:{rows_impacted}")
print(f"OrderIds impacted handling Quantity Missing Values:{orderids}")

Rows impacted by Quantity Missing Values:18
OrderIds impacted handling Quantity Missing Values:17

***DATA MASKING AND STRING HANDLING***

In [38]:
df[['Customer ID','Customer Name']].head()

  Customer ID    Customer Name
0    CG-12520      Claire Gute
1    CG-12520      Claire Gute
2    DV-13045  Darrin Van Huff
3    SO-20335   Sean O'Donnell
4    SO-20335   Sean O'Donnell

In [39]:
df.drop(columns=['Customer Name'], inplace=True)
df['Customer Name Masked']=df['Customer ID'].apply(lambda x: x.split('-')[0])
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year,Days to Ship,Customer Name Masked
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,2016,2016,3,CG
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,2016,2016,3,CG
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,2016,2016,4,DV
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,2015,2015,7,SO
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,2015,2015,7,SO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200,2017,2017,5,DB
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480,2017,2017,5,CC
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110,2014,2014,0,ZD
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872,2015,2015,2,FA
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835,2017,2017,3,NS

In [40]:
df['Postal Code'].unique()

array([42420, 90036, 33311, 90032, 28027, 98103, 76106, 53711, 84084,
       94109, 68025, 19140, 84057, 90049, 77095, 75080, 77041, 60540,
       32935, 55122, 48185, 19901, 47150, 10024, 12180, 90004, 60610,
       85234, 22153, 10009, 49201, 38109, 77070, 35601, 94122, 27707,
       60623, 29203, 55901, 55407, 97206, 55106, 80013, 28205, 60462,
       10035, 50322, 43229, 37620, 19805, 61701, 85023, 95661, 64055,
       91104, 43055, 53132, 85254, 95123, 98105, 98115, 73034, 90045,
       19134, 88220, 78207, 77036, 62521, 71203,  6824, 75051, 92374,
       45011,  7090, 19120, 44312, 80219, 75220, 37064, 90604, 48601,
       44256, 43017, 48227, 38401, 33614, 95051, 55044, 92037, 77506,
       94513, 27514,  7960, 45231, 94110, 90301, 33319, 80906,  7109,
       48180,  8701, 22204, 80004,  7601, 33710, 19143, 90805, 92345,
       37130, 84041, 78745,  1852, 31907,  6040, 78550, 85705, 62301,
        2038, 33024, 98198, 61604, 89115,  2886, 33180, 28403, 92646,
       40475, 80027,  1841, 39212, 48187, 10801, 28052, 32216, 47201,
       13021, 73071, 94521, 60068, 79109, 11757, 90008, 92024, 77340,
       14609, 72701, 92627, 80134, 30318, 64118, 59405, 48234, 33801,
       36116, 85204, 60653, 54302, 45503, 92804, 98270, 97301, 78041,
       75217, 43123, 10011, 48126, 31088, 94591, 92691, 48307,  7060,
       85635, 98661, 60505, 76017, 40214, 75081, 44105, 75701, 27217,
       22980, 19013, 27511, 32137, 10550, 48205, 33012, 11572, 92105,
       60201, 48183, 55016, 71111, 50315, 93534, 23223, 28806, 92530,
       68104, 98026, 92704, 53209, 41042, 44052,  7036, 93905,  8901,
       17602,  3301, 21044, 75043,  6360, 22304, 43615, 87401, 92503,
       90503, 78664, 92054, 33433, 23464, 92563, 28540, 52601, 98502,
       20016, 65109, 63376, 61107, 33142, 78521, 10701, 94601, 28110,
       20735, 30076, 72401, 47374, 94509, 33030, 46350, 48911, 44221,
       89502, 22801, 92025, 48073, 20852, 33065, 14215, 33437, 39503,
       93727, 27834, 11561, 35630, 31204, 52402,  2908, 81001, 94533,
       32725, 42071,  6457, 11520, 90660, 84604, 84062, 30080, 24153,
       44134, 36608,  2740, 75061,  8360, 85301, 14304, 27360, 92683,
       38301, 75019, 91767, 89031, 18103, 19711, 85281, 92677,  8302,
        2149, 13601, 54915, 98006, 75002, 79907, 76051, 75007, 37167,
       98031, 70506, 97224, 60076, 75023, 23434, 46203,  7002, 28314,
       27405, 21215, 53142, 66062, 98002, 74133, 97756, 27604, 74403,
        6450, 42104, 46614,  6010, 89015, 99207, 76248, 45014, 32127,
       97504, 22901, 59801, 33178, 29501, 97477, 32712, 19601, 80020,
       65807,  7501, 73120, 23320, 79424, 65203, 37604, 36830, 92404,
        1453, 59715, 85345, 44107,  8861, 91761, 91730, 56560, 75150,
       95207, 32174, 94086,  3820, 17403, 77840, 63116,  2169, 95336,
       44240, 76903, 84106, 35810, 37918, 72209, 48146, 43302, 80122,
        5408,  4401, 38671, 47362, 48640, 57103, 80525, 47905, 37042,
       95823, 91360,  2148,  1040, 87105, 89431, 92236, 60126,  7055,
       29406, 23602, 14701, 46544, 43402, 92253, 32303, 37211, 98226,
       60098, 76117, 60090, 29483, 71901, 80112, 43130, 88001, 35244,
       75034, 95687, 84107, 53186, 93309, 33068, 45373, 78415, 90278,
       32839,  7050, 70601, 60035, 11550, 46060, 55124, 29464, 48310,
       54703, 78577, 59102, 97030, 37421, 83642, 92307, 60440, 55369,
       95695, 77489, 77581, 94403, 49505, 93277, 66212, 92592, 92399,
        2151, 77301, 60477, 52001, 48127, 87505, 28601, 60188, 56301,
       33161, 46226, 33317, 34952, 29730, 79762, 53214, 91911, 66502,
       16602, 80229, 61821, 47401, 71854, 78539, 77520, 46142, 90712,
        2895, 54880, 76021, 98042, 74012, 33023, 33021, 77536, 67212,
       78501, 52240, 83704,  2920, 61032, 77642, 95610, 75056, 98052,
       32114, 86442, 46368, 58103, 46514, 91776, 33063, 30328, 44060,
       73505, 23666, 13440, 54601, 83501, 39401, 94526, 48858, 84321,
        6708, 30605,  4240, 61832, 85323, 30062, 85364, 54401, 99301,
       60302, 32503, 77573, 20877, 84043, 35401, 92553, 40324, 80538,
       85224, 59601, 63122, 76706, 48066, 60423, 18018, 55113, 68801,
       55125, 48237, 72756, 88101, 33458, 93101, 75104, 68701, 84020,
       48104, 91941, 83201, 49423,  6460, 60089, 92630, 96003, 95928,
       13501, 72032, 82001, 42301, 83605, 70065,  3060, 38134, 94061,
       37087, 93454, 60016, 98632, 37075, 50701,  2138, 60067,  1915,
       97405, 93030, 98059, 60025, 33445, 80022, 77590, 27893, 87124,
       27534, 98208, 90640, 92020, 77705, 33407, 79605, 61761, 63301,
       60174, 93010, 97123, 91505, 95351, 67846,  8401, 80501, 95616,
       26003, 95037,  7011, 53081, 30344, 57701,  1810, 34741,  6484,
        6810, 52302, 32771, 78666, 80634, 76063, 44035, 83301, 33134,
       60441,  1752, 20707, 77803, 71603, 57401, 21740,  7017, 60004,
       60543, 55433, 92672, 94568, 93405, 72762, 95240, 77571, 45040,
       30188])

In [41]:
df['Postal Code']=df['Postal Code'].astype(str).str.zfill(5)
df['Postal Code'].unique()

array(['42420', '90036', '33311', '90032', '28027', '98103', '76106',
       '53711', '84084', '94109', '68025', '19140', '84057', '90049',
       '77095', '75080', '77041', '60540', '32935', '55122', '48185',
       '19901', '47150', '10024', '12180', '90004', '60610', '85234',
       '22153', '10009', '49201', '38109', '77070', '35601', '94122',
       '27707', '60623', '29203', '55901', '55407', '97206', '55106',
       '80013', '28205', '60462', '10035', '50322', '43229', '37620',
       '19805', '61701', '85023', '95661', '64055', '91104', '43055',
       '53132', '85254', '95123', '98105', '98115', '73034', '90045',
       '19134', '88220', '78207', '77036', '62521', '71203', '06824',
       '75051', '92374', '45011', '07090', '19120', '44312', '80219',
       '75220', '37064', '90604', '48601', '44256', '43017', '48227',
       '38401', '33614', '95051', '55044', '92037', '77506', '94513',
       '27514', '07960', '45231', '94110', '90301', '33319', '80906',
       '07109', '48180', '08701', '22204', '80004', '07601', '33710',
       '19143', '90805', '92345', '37130', '84041', '78745', '01852',
       '31907', '06040', '78550', '85705', '62301', '02038', '33024',
       '98198', '61604', '89115', '02886', '33180', '28403', '92646',
       '40475', '80027', '01841', '39212', '48187', '10801', '28052',
       '32216', '47201', '13021', '73071', '94521', '60068', '79109',
       '11757', '90008', '92024', '77340', '14609', '72701', '92627',
       '80134', '30318', '64118', '59405', '48234', '33801', '36116',
       '85204', '60653', '54302', '45503', '92804', '98270', '97301',
       '78041', '75217', '43123', '10011', '48126', '31088', '94591',
       '92691', '48307', '07060', '85635', '98661', '60505', '76017',
       '40214', '75081', '44105', '75701', '27217', '22980', '19013',
       '27511', '32137', '10550', '48205', '33012', '11572', '92105',
       '60201', '48183', '55016', '71111', '50315', '93534', '23223',
       '28806', '92530', '68104', '98026', '92704', '53209', '41042',
       '44052', '07036', '93905', '08901', '17602', '03301', '21044',
       '75043', '06360', '22304', '43615', '87401', '92503', '90503',
       '78664', '92054', '33433', '23464', '92563', '28540', '52601',
       '98502', '20016', '65109', '63376', '61107', '33142', '78521',
       '10701', '94601', '28110', '20735', '30076', '72401', '47374',
       '94509', '33030', '46350', '48911', '44221', '89502', '22801',
       '92025', '48073', '20852', '33065', '14215', '33437', '39503',
       '93727', '27834', '11561', '35630', '31204', '52402', '02908',
       '81001', '94533', '32725', '42071', '06457', '11520', '90660',
       '84604', '84062', '30080', '24153', '44134', '36608', '02740',
       '75061', '08360', '85301', '14304', '27360', '92683', '38301',
       '75019', '91767', '89031', '18103', '19711', '85281', '92677',
       '08302', '02149', '13601', '54915', '98006', '75002', '79907',
       '76051', '75007', '37167', '98031', '70506', '97224', '60076',
       '75023', '23434', '46203', '07002', '28314', '27405', '21215',
       '53142', '66062', '98002', '74133', '97756', '27604', '74403',
       '06450', '42104', '46614', '06010', '89015', '99207', '76248',
       '45014', '32127', '97504', '22901', '59801', '33178', '29501',
       '97477', '32712', '19601', '80020', '65807', '07501', '73120',
       '23320', '79424', '65203', '37604', '36830', '92404', '01453',
       '59715', '85345', '44107', '08861', '91761', '91730', '56560',
       '75150', '95207', '32174', '94086', '03820', '17403', '77840',
       '63116', '02169', '95336', '44240', '76903', '84106', '35810',
       '37918', '72209', '48146', '43302', '80122', '05408', '04401',
       '38671', '47362', '48640', '57103', '80525', '47905', '37042',
       '95823', '91360', '02148', '01040', '87105', '89431', '92236',
       '60126', '07055', '29406', '23602', '14701', '46544', '43402',
       '92253', '32303', '37211', '98226', '60098', '76117', '60090',
       '29483', '71901', '80112', '43130', '88001', '35244', '75034',
       '95687', '84107', '53186', '93309', '33068', '45373', '78415',
       '90278', '32839', '07050', '70601', '60035', '11550', '46060',
       '55124', '29464', '48310', '54703', '78577', '59102', '97030',
       '37421', '83642', '92307', '60440', '55369', '95695', '77489',
       '77581', '94403', '49505', '93277', '66212', '92592', '92399',
       '02151', '77301', '60477', '52001', '48127', '87505', '28601',
       '60188', '56301', '33161', '46226', '33317', '34952', '29730',
       '79762', '53214', '91911', '66502', '16602', '80229', '61821',
       '47401', '71854', '78539', '77520', '46142', '90712', '02895',
       '54880', '76021', '98042', '74012', '33023', '33021', '77536',
       '67212', '78501', '52240', '83704', '02920', '61032', '77642',
       '95610', '75056', '98052', '32114', '86442', '46368', '58103',
       '46514', '91776', '33063', '30328', '44060', '73505', '23666',
       '13440', '54601', '83501', '39401', '94526', '48858', '84321',
       '06708', '30605', '04240', '61832', '85323', '30062', '85364',
       '54401', '99301', '60302', '32503', '77573', '20877', '84043',
       '35401', '92553', '40324', '80538', '85224', '59601', '63122',
       '76706', '48066', '60423', '18018', '55113', '68801', '55125',
       '48237', '72756', '88101', '33458', '93101', '75104', '68701',
       '84020', '48104', '91941', '83201', '49423', '06460', '60089',
       '92630', '96003', '95928', '13501', '72032', '82001', '42301',
       '83605', '70065', '03060', '38134', '94061', '37087', '93454',
       '60016', '98632', '37075', '50701', '02138', '60067', '01915',
       '97405', '93030', '98059', '60025', '33445', '80022', '77590',
       '27893', '87124', '27534', '98208', '90640', '92020', '77705',
       '33407', '79605', '61761', '63301', '60174', '93010', '97123',
       '91505', '95351', '67846', '08401', '80501', '95616', '26003',
       '95037', '07011', '53081', '30344', '57701', '01810', '34741',
       '06484', '06810', '52302', '32771', '78666', '80634', '76063',
       '44035', '83301', '33134', '60441', '01752', '20707', '77803',
       '71603', '57401', '21740', '07017', '60004', '60543', '55433',
       '92672', '94568', '93405', '72762', '95240', '77571', '45040',
       '30188'], dtype=object)

In [42]:
#Data Type Conversion 
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Sales Price']=pd.to_numeric(df['Sales Price'],errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9997 non-null   int64
 1   Order ID              9997 non-null   object
 2   Order Date            9997 non-null   datetime64[ns]
 3   Ship Date             9997 non-null   datetime64[ns]
 4   Ship Mode             9997 non-null   object
 5   Customer ID           9997 non-null   object
 6   Segment               9997 non-null   object
 7   Country               9997 non-null   object
 8   City                  9997 non-null   object
 9   State                 9997 non-null   object
 10  Postal Code           9997 non-null   object
 11  Region                9997 non-null   object
 12  Product ID            9997 non-null   object
 13  Category              9997 non-null   object
 14  Sub-Category          9997 non-null   object
 15  Product Name          9997 non-null   object
 16  Sales Price           9997 non-null   float64
 17  Quantity              9997 non-null   float64
 18  Discount              9997 non-null   float64
 19  Profit                9997 non-null   float64
 20  OrderID Year          9997 non-null   int64
 21  OrderDate Year        9997 non-null   int32
 22  Days to Ship          9997 non-null   int64
 23  Customer Name Masked  9997 non-null   object
dtypes: datetime64[ns](2), float64(4), int32(1), int64(3), object(14)
memory usage: 2.1+ MB

In [43]:
#Handling Inconsistent Categorical Data
df['State'].value_counts()

State
California              1906
New York                1105
Texas                    918
Pennsylvania             587
Illinois                 493
Ohio                     469
Washington               457
Florida                  383
Michigan                 255
North Carolina           250
Virginia                 224
Arizona                  224
Georgia                  184
Tennessee                183
Colorado                 182
Indiana                  149
Kentucky                 139
Massachusetts            135
Oregon                   124
Wisconsin                110
Maryland                 105
New Jersey                99
Delaware                  96
CA                        96
Minnesota                 89
Connecticut               82
TX                        67
Missouri                  66
Oklahoma                  66
Alabama                   61
Arkansas                  60
Rhode Island              56
Utah                      53
Mississippi               53
WA\                       49
South Carolina            42
Louisiana                 42
Nevada                    39
Nebraska                  38
New Mexico                37
NJ                        31
Iowa                      30
New Hampshire             27
Kansas                    24
NY                        23
Idaho                     21
Montana                   15
South Dakota              12
Vermont                   11
District of Columbia      10
Maine                      8
North Dakota               7
West Virginia              4
Wyoming                    1
Name: count, dtype: int64

In [44]:
df['State']=(
    df['State'].str.strip()
    .str.strip(r'\/.-_ ')
)
state_mapping={
    'CA':'California',
    'TX': 'Texas',
    'WA': 'Washington',
    'NY': 'New York',
    'NJ': 'New Jersey'
}
df['State']=df['State'].replace(state_mapping)

In [45]:
df['State'].value_counts()

State
California              2002
New York                1128
Texas                    985
Pennsylvania             587
Washington               506
Illinois                 493
Ohio                     469
Florida                  383
Michigan                 255
North Carolina           250
Arizona                  224
Virginia                 224
Georgia                  184
Tennessee                183
Colorado                 182
Indiana                  149
Kentucky                 139
Massachusetts            135
New Jersey               130
Oregon                   124
Wisconsin                110
Maryland                 105
Delaware                  96
Minnesota                 89
Connecticut               82
Missouri                  66
Oklahoma                  66
Alabama                   61
Arkansas                  60
Rhode Island              56
Utah                      53
Mississippi               53
South Carolina            42
Louisiana                 42
Nevada                    39
Nebraska                  38
New Mexico                37
Iowa                      30
New Hampshire             27
Kansas                    24
Idaho                     21
Montana                   15
South Dakota              12
Vermont                   11
District of Columbia      10
Maine                      8
North Dakota               7
West Virginia              4
Wyoming                    1
Name: count, dtype: int64

In [46]:
#Feature Engineering
df['Original Price']=df['Sales Price']/ (1-df['Discount'])
df['Discount Price']=df['Discount']*df['Original Price']
df['Total Sales']=df['Sales Price']*df['Quantity']
df['Total Discount']=df['Discount Price']*df['Quantity']
df['Total Profit']=df['Profit']*df['Quantity']
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,Profit,OrderID Year,OrderDate Year,Days to Ship,Customer Name Masked,Original Price,Discount Price,Total Sales,Total Discount,Total Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,41.9136,2016,2016,3,CG,261.96,0.0000,523.9200,0.0000,83.8272
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,219.5820,2016,2016,3,CG,731.94,0.0000,2195.8200,0.0000,658.7460
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,6.8714,2016,2016,4,DV,14.62,0.0000,29.2400,0.0000,13.7428
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,-383.0310,2015,2015,7,SO,1741.05,783.4725,4787.8875,3917.3625,-1915.1550
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,2.5164,2015,2015,7,SO,27.96,5.5920,44.7360,11.1840,5.0328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,13.3200,2017,2017,5,DB,29.60,0.0000,118.4000,0.0000,53.2800
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,72.9480,2017,2017,5,CC,243.16,0.0000,486.3200,0.0000,145.8960
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,16.0110,2014,2014,0,ZD,266.85,53.3700,640.4400,160.1100,48.0330
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,3.2872,2015,2015,2,FA,-11.74,-2.3480,-18.7840,-4.6960,6.5744
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,2.9835,2017,2017,3,NS,-11.05,-2.2100,-44.2000,-11.0500,14.9175

In [47]:
df['Days to Ship'].unique()

array([   3,    4,    7,    0,    5,    2,    6,    1, -359, -360, -363])

In [48]:
df['Days to Ship'].value_counts()

Days to Ship
 0      2372
 4      2202
 5      1692
 2      1049
 6       996
 3       837
 7       517
 1       325
-359       5
-360       1
-363       1
Name: count, dtype: int64

In [49]:
days_issue=df['Days to Ship'] < 0
days_issue

0        False
1        False
2        False
3        False
4        False
         ...
9992     False
9993     False
9998     False
10000    False
10005    False
Name: Days to Ship, Length: 9997, dtype: bool

In [50]:
df.loc[days_issue,'Ship Date']=(
    df.loc[days_issue, 'Ship Date'] + pd.DateOffset(years=1)
)
df['Days to Ship']=(df['Ship Date']-df['Order Date']).dt.days

In [51]:
df['Days to Ship'].value_counts()

Days to Ship
0    2372
4    2202
5    1693
2    1050
6    1001
3     837
7     517
1     325
Name: count, dtype: int64

In [52]:
df['Shipping Urgency']=df['Days to Ship'].apply(
    lambda x: 'Immediate' if x==0
    else ('Urgent' if 1 <= x <= 3
    else 'Standard')
)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,OrderID Year,OrderDate Year,Days to Ship,Customer Name Masked,Original Price,Discount Price,Total Sales,Total Discount,Total Profit,Shipping Urgency
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,2016,2016,3,CG,261.96,0.0000,523.9200,0.0000,83.8272,Urgent
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,2016,2016,3,CG,731.94,0.0000,2195.8200,0.0000,658.7460,Urgent
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,2016,2016,4,DV,14.62,0.0000,29.2400,0.0000,13.7428,Standard
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,2015,2015,7,SO,1741.05,783.4725,4787.8875,3917.3625,-1915.1550,Standard
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,2015,2015,7,SO,27.96,5.5920,44.7360,11.1840,5.0328,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,2017,2017,5,DB,29.60,0.0000,118.4000,0.0000,53.2800,Standard
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,2017,2017,5,CC,243.16,0.0000,486.3200,0.0000,145.8960,Standard
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,2014,2014,0,ZD,266.85,53.3700,640.4400,160.1100,48.0330,Immediate
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,2015,2015,2,FA,-11.74,-2.3480,-18.7840,-4.6960,6.5744,Urgent
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,2017,2017,3,NS,-11.05,-2.2100,-44.2000,-11.0500,14.9175,Urgent

In [53]:
df['Shipping Urgency'].value_counts()

Shipping Urgency
Standard     5413
Immediate    2372
Urgent       2212
Name: count, dtype: int64

In [54]:
df['Days Since Last Order']=(
    df.sort_values(['Customer ID','Order Date'])
    .groupby('Customer ID')['Order Date']
    .diff().dt.days
)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,OrderDate Year,Days to Ship,Customer Name Masked,Original Price,Discount Price,Total Sales,Total Discount,Total Profit,Shipping Urgency,Days Since Last Order
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,2016,3,CG,261.96,0.0000,523.9200,0.0000,83.8272,Urgent,390.0
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,2016,3,CG,731.94,0.0000,2195.8200,0.0000,658.7460,Urgent,0.0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,2016,4,DV,14.62,0.0000,29.2400,0.0000,13.7428,Standard,NaN
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,2015,7,SO,1741.05,783.4725,4787.8875,3917.3625,-1915.1550,Standard,NaN
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,2015,7,SO,27.96,5.5920,44.7360,11.1840,5.0328,Standard,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,2017,5,DB,29.60,0.0000,118.4000,0.0000,53.2800,Standard,0.0
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,2017,5,CC,243.16,0.0000,486.3200,0.0000,145.8960,Standard,215.0
9998,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,2014,0,ZD,266.85,53.3700,640.4400,160.1100,48.0330,Immediate,0.0
10000,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,2015,2,FA,-11.74,-2.3480,-18.7840,-4.6960,6.5744,Urgent,0.0
10005,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,2017,3,NS,-11.05,-2.2100,-44.2000,-11.0500,14.9175,Urgent,0.0

In [55]:
customer_wise_sales=(
    df.groupby('Customer ID')[['Total Sales','Total Discount','Quantity']]
    .sum().reset_index()
)
customer_wise_sales.columns=['Customer ID','Total Sales Per Customer','Total Discount Per Customer','Total Quantity Per Customer']
customer_wise_sales

,Customer ID,Total Sales Per Customer,Total Discount Per Customer,Total Quantity Per Customer
0,AA-10315,16073.344,3681.906,30.0
1,AA-10375,2734.830,188.540,41.0
2,AA-10480,5493.936,11.664,36.0
3,AA-10645,22927.855,3342.735,64.0
4,AB-10015,1984.480,18.490,13.0
...,...,...,...,...
788,XP-21865,8676.214,908.116,100.0
789,YC-21895,27208.926,1106.694,31.0
790,YS-21880,46478.992,6947.658,58.0
791,ZC-21910,40212.889,21865.921,105.0
792,ZD-21925,7132.888,1401.782,35.0

In [56]:
df=pd.merge(df,customer_wise_sales, on='Customer ID', how='left')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,Original Price,Discount Price,Total Sales,Total Discount,Total Profit,Shipping Urgency,Days Since Last Order,Total Sales Per Customer,Total Discount Per Customer,Total Quantity Per Customer
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,261.96,0.0000,523.9200,0.0000,83.8272,Urgent,390.0,3549.6600,1192.8000,14.0
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,731.94,0.0000,2195.8200,0.0000,658.7460,Urgent,0.0,3549.6600,1192.8000,14.0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,14.62,0.0000,29.2400,0.0000,13.7428,Standard,NaN,6156.8940,4212.3260,28.0
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,1741.05,783.4725,4787.8875,3917.3625,-1915.1550,Standard,NaN,10343.1775,4553.4825,52.0
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,27.96,5.5920,44.7360,11.1840,5.0328,Standard,0.0,10343.1775,4553.4825,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,29.60,0.0000,118.4000,0.0000,53.2800,Standard,0.0,20617.7460,4077.8440,48.0
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,243.16,0.0000,486.3200,0.0000,145.8960,Standard,215.0,20295.6020,7693.0380,81.0
9994,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,266.85,53.3700,640.4400,160.1100,48.0330,Immediate,0.0,7132.8880,1401.7820,35.0
9995,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,-11.74,-2.3480,-18.7840,-4.6960,6.5744,Urgent,0.0,9489.7560,2572.8240,60.0
9996,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,-11.05,-2.2100,-44.2000,-11.0500,14.9175,Urgent,0.0,12772.4770,6183.8830,118.0

In [57]:
#Outlier Detection & Handling
negative_sales=df[df['Sales Price']<0]

In [58]:
def remove_outliers(df, column):
    Q1=df[column].quantile(0.25)
    Q3=df[column].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-(3*IQR)
    upper_bound=Q1+(3*IQR)

    outliers=df[(df[column]< lower_bound) | (df[column]> upper_bound)]
    print(f"Outliers found: {outliers.shape[0]} rows")

    df_cleaned=df[~((df[column]< lower_bound) | (df[column]> upper_bound))]

    return df_cleaned

df=remove_outliers(df,'Sales Price')
df

Outliers found: 957 rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,...,Original Price,Discount Price,Total Sales,Total Discount,Total Profit,Shipping Urgency,Days Since Last Order,Total Sales Per Customer,Total Discount Per Customer,Total Quantity Per Customer
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,261.96,0.000,523.920,0.000,83.8272,Urgent,390.0,3549.6600,1192.8000,14.0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Corporate,United States,Los Angeles,California,...,14.62,0.000,29.240,0.000,13.7428,Standard,NaN,6156.8940,4212.3260,28.0
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,27.96,5.592,44.736,11.184,5.0328,Standard,0.0,10343.1775,4553.4825,52.0
5,6,CA-2014-115812,2014-06-09,2014-06-09,Same Day,BH-11710,Consumer,United States,Los Angeles,California,...,48.86,0.000,342.020,0.000,99.1858,Immediate,NaN,36995.1770,7866.3930,97.0
6,7,CA-2014-115812,2014-06-09,2014-06-09,Same Day,BH-11710,Consumer,United States,Los Angeles,California,...,7.28,0.000,29.120,0.000,7.8624,Immediate,0.0,36995.1770,7866.3930,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,...,29.60,0.000,118.400,0.000,53.2800,Standard,0.0,20617.7460,4077.8440,48.0
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Consumer,United States,Westminster,California,...,243.16,0.000,486.320,0.000,145.8960,Standard,215.0,20295.6020,7693.0380,81.0
9994,20,CA-2014-143336,2014-08-27,2014-08-27,Same Day,ZD-21925,Consumer,United States,San Francisco,California,...,266.85,53.370,640.440,160.110,48.0330,Immediate,0.0,7132.8880,1401.7820,35.0
9995,8852,CA-2015-140718,2015-07-02,2015-07-04,First Class,FA-14230,Corporate,United States,Raleigh,North Carolina,...,-11.74,-2.348,-18.784,-4.696,6.5744,Urgent,0.0,9489.7560,2572.8240,60.0
9996,1044,CA-2017-115651,2017-07-09,2017-07-12,First Class,NS-18640,Corporate,United States,Chicago,Illinois,...,-11.05,-2.210,-44.200,-11.050,14.9175,Urgent,0.0,12772.4770,6183.8830,118.0

In [59]:
df.shape

(9040, 34)