In [1]:
import pandas as pd
#Loading dataset
df=pd.read_csv('SuperStore_EDA_v1.csv')

# Intial Exloration of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10014 entries, 0 to 10013
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10014 non-null  int64
 1   Order ID       10014 non-null  object
 2   Order Date     10014 non-null  object
 3   Ship Date      10014 non-null  object
 4   Ship Mode      9916 non-null   object
 5   Customer ID    10014 non-null  object
 6   Customer Name  10014 non-null  object
 7   Segment        10014 non-null  object
 8   Country        10014 non-null  object
 9   City           10014 non-null  object
 10  State          10014 non-null  object
 11  Postal Code    10014 non-null  int64
 12  Region         10014 non-null  object
 13  Product ID     10014 non-null  object
 14  Category       10014 non-null  object
 15  Sub-Category   10014 non-null  object
 16  Product Name   10014 non-null  object
 17  Sales Price    10014 non-null  float64
 18  Quantity       9996 non-null   float64
 19  Discount       10014 non-null  float64
 20  Profit         10014 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,12/06/16,16/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [3]:
df.shape

(10014, 21)

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales Price', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
#Data Types
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales Price      float64
Quantity         float64
Discount         float64
Profit           float64
dtype: object

In [6]:
#Summary Statistics
df.describe()

,Row ID,Postal Code,Sales Price,Quantity,Discount,Profit
count,10014.000000,10014.000000,10014.000000,9996.000000,10014.000000,10014.000000
mean,4997.523367,55205.131616,230.038424,3.792517,0.156240,28.708317
std,2888.981754,32066.711027,623.057359,2.231021,0.206392,234.154272
min,1.000000,1040.000000,-31.500000,1.000000,0.000000,-6599.978000
25%,2494.250000,23223.000000,17.280000,2.000000,0.000000,1.731375
50%,4997.500000,57103.000000,54.780000,3.000000,0.200000,8.666500
75%,7500.750000,90008.000000,209.970000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [7]:
#Summary Statistics
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
count,10014.000000,10014,10014,10014,9916,10014,10014,10014,10014,10014,...,10014.000000,10014,10014,10014,10014,10014,10014.000000,9996.000000,10014.000000,10014.000000
unique,NaN,5009,1240,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,05/09/16,16/12/15,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5908,37,37,5203,10014,917,...,NaN,3212,19,6037,1526,48,NaN,NaN,NaN,NaN
mean,4997.523367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55205.131616,NaN,NaN,NaN,NaN,NaN,230.038424,3.792517,0.156240,28.708317
std,2888.981754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32066.711027,NaN,NaN,NaN,NaN,NaN,623.057359,2.231021,0.206392,234.154272
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,-31.500000,1.000000,0.000000,-6599.978000
25%,2494.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.731375
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57103.000000,NaN,NaN,NaN,NaN,NaN,54.780000,3.000000,0.200000,8.666500
75%,7500.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.970000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [8]:
#Unique Values Count
df.nunique()

Row ID           9994
Order ID         5009
Order Date       1240
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              54
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1850
Sales Price      5829
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [9]:
#Missing or discrepancies Values
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode        98
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales Price       0
Quantity         18
Discount          0
Profit            0
dtype: int64

**IDENTIFY DATA QUALITY ISSUES**

In [10]:
#Dropping duplicates
rows_before=len(df)
orderids_before=df['Order ID'].nunique()

df=df.drop_duplicates()

rows_after=len(df)
orderids_after=df['Order ID'].nunique()
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,12/06/16,16/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,11/10/15,18/10/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,26/02/17,03/03/17,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994,CA-2017-119914,04/05/17,09/05/17,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480
9998,20,CA-2014-143336,27/08/14,2014-9-1,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110
10000,8852,CA-2015-140718,02/07/15,04/07/15,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,27604,South,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872
10005,1044,CA-2017-115651,09/07/17,12/07/17,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,60610,Central,OFF-AR-10001130,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835

In [11]:
#Data Exploration after dropping duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9997 non-null   int64
 1   Order ID       9997 non-null   object
 2   Order Date     9997 non-null   object
 3   Ship Date      9997 non-null   object
 4   Ship Mode      9899 non-null   object
 5   Customer ID    9997 non-null   object
 6   Customer Name  9997 non-null   object
 7   Segment        9997 non-null   object
 8   Country        9997 non-null   object
 9   City           9997 non-null   object
 10  State          9997 non-null   object
 11  Postal Code    9997 non-null   int64
 12  Region         9997 non-null   object
 13  Product ID     9997 non-null   object
 14  Category       9997 non-null   object
 15  Sub-Category   9997 non-null   object
 16  Product Name   9997 non-null   object
 17  Sales Price    9997 non-null   float64
 18  Quantity       9979 non-null   float64
 19  Discount       9997 non-null   float64
 20  Profit         9997 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.7+ MB

In [12]:
#Data Affected
print("Duplicate Removal Report")
print(f"Intital Rows:{rows_before}   After Removal: {rows_after}")
print(f"Intital Distinct OrderIds:{orderids_before}   After Removal: {orderids_after}")

Duplicate Removal Report
Intital Rows:10014   After Removal: 9997
Intital Distinct OrderIds:5009   After Removal: 5009

***DATA HANDLING***

In [13]:
#Before Data Handling Rows and OrderIds
rows_before=len(df)
orderids_before=df['Order ID'].nunique()

In [14]:
#Normalizing Order Data and Ship Date
df['Order Date']=pd.to_datetime(df['Order Date'], format='mixed', errors='coerce')
df['Ship Date']=pd.to_datetime(df['Ship Date'],  format='mixed',errors='coerce')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,2016-12-06,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,2015-11-10,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,2015-11-10,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994,CA-2017-119914,2017-04-05,2017-09-05,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480
9998,20,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3.0,0.20,16.0110
10000,8852,CA-2015-140718,2015-02-07,2015-04-07,First Class,FA-14230,Frank Atkinson,Corporate,United States,Raleigh,...,27604,South,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,-9.3920,2.0,0.20,3.2872
10005,1044,CA-2017-115651,2017-09-07,2017-12-07,First Class,NS-18640,Noel Staavos,Corporate,United States,Chicago,...,60610,Central,OFF-AR-10001130,Office Supplies,Art,"Quartet Alpha White Chalk, 12/Pack",-8.8400,5.0,0.20,2.9835

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 10005
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9997 non-null   int64
 1   Order ID       9997 non-null   object
 2   Order Date     9997 non-null   datetime64[ns]
 3   Ship Date      9997 non-null   datetime64[ns]
 4   Ship Mode      9899 non-null   object
 5   Customer ID    9997 non-null   object
 6   Customer Name  9997 non-null   object
 7   Segment        9997 non-null   object
 8   Country        9997 non-null   object
 9   City           9997 non-null   object
 10  State          9997 non-null   object
 11  Postal Code    9997 non-null   int64
 12  Region         9997 non-null   object
 13  Product ID     9997 non-null   object
 14  Category       9997 non-null   object
 15  Sub-Category   9997 non-null   object
 16  Product Name   9997 non-null   object
 17  Sales Price    9997 non-null   float64
 18  Quantity       9979 non-null   float64
 19  Discount       9997 non-null   float64
 20  Profit         9997 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.7+ MB

In [16]:
df['OrderID Year']=df['Order ID'].apply(lambda x: int(x.split('-')[1]))
df['OrderDate Year']=df['Order Date'].dt.year
year_inconsistences=df[df['OrderID Year'] !=df['OrderDate Year']]
year_inconsistences

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Profit,OrderID Year,OrderDate Year
62,63,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,TEC-AC-10004633,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,13.980,2.0,0.0,6.1512,2015,2017
63,64,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-BI-10001078,Office Supplies,Binders,"Acco PRESSTEX Data Binder with Storage Hooks, ...",25.824,6.0,0.2,9.3612,2015,2017
64,65,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,OFF-PA-10003892,Office Supplies,Paper,Xerox 1943,146.730,3.0,0.0,68.9631,2015,2017
65,66,CA-2015-135545,2017-11-24,2015-11-30,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,FUR-FU-10000397,Furniture,Furnishings,Luxo Economy Swing Arm Lamp,79.760,4.0,0.0,22.3328,2015,2017
943,944,CA-2015-120880,2013-05-29,2015-03-06,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,32.400,5.0,0.0,15.5520,2015,2013
944,945,CA-2015-120880,2013-05-29,2015-03-06,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-ST-10001496,Office Supplies,Storage,Standard Rollaway File with Lock,540.570,3.0,0.0,140.5482,2015,2013
945,946,CA-2015-120880,2013-05-29,2015-03-06,Standard Class,JL-15850,John Lucas,Consumer,United States,Seattle,...,OFF-BI-10002931,Office Supplies,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",167.760,5.0,0.2,62.9100,2015,2013
1152,1153,CA-2017-160395,2016-12-31,2017-06-01,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-AR-10003759,Office Supplies,Art,"Crayola Anti Dust Chalk, 12/Pack",3.640,2.0,0.0,1.6380,2017,2016
1153,1154,CA-2017-160395,2016-12-31,2017-06-01,Standard Class,KL-16555,Kelly Lampkin,Corporate,United States,Reno,...,OFF-BI-10003984,Office Supplies,Binders,Lock-Up Easel 'Spel-Binder',159.768,7.0,0.2,53.9217,2017,2016
2752,2753,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AR-10003251,Office Supplies,Art,Prang Drawing Pencil Set,5.560,2.0,0.0,2.2240,2015,1999
2753,2754,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,323.370,3.0,0.0,129.3480,2015,1999
2754,2755,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,TEC-PH-10002310,Technology,Phones,Plantronics Calisto P620-M USB Wireless Speake...,783.960,5.0,0.2,68.5965,2015,1999
2755,2756,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-AP-10002651,Office Supplies,Appliances,Hoover Upright Vacuum With Dirt Cup,1447.650,5.0,0.0,419.8185,2015,1999
2756,2757,CA-2015-155306,1999-04-17,2015-04-21,Standard Class,GA-14515,George Ashbrook,Consumer,United States,San Francisco,...,OFF-PA-10001184,Office Supplies,Paper,Xerox 1903,11.960,2.0,0.0,5.8604,2015,1999
2821,2822,CA-2017-100202,2016-12-31,2017-05-01,Standard Class,BD-11620,Brian DeCherney,Consumer,United States,Anaheim,...,TEC-PH-10002563,Technology,Phones,Adtran 1202752G1,302.376,3.0,0.2,22.6782,2017,2016
3537,3538,CA-2014-158771,2015-09-05,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3.0,0.0,14.9850,2014,2015
3538,3539,CA-2014-158771,2015-09-05,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3.0,0.0,4.5360,2014,2015
3539,3540,CA-2014-158771,2015-09-05,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-LA-10003121,Office Supplies,Labels,Avery 506,20.650,5.0,0.0,9.4990,2014,2015
3540,3541,CA-2014-158771,2015-09-05,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7.0,0.0,21.7728,2014,2015
4448,4449,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,FUR-FU-10000732,Furniture,Furnishings,Eldon 200 Class Desk Accessories,12.560,2.0,0.0,4.0192,2015,2017
4449,4450,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-PA-10004355,Office Supplies,Paper,Xerox 231,6.480,1.0,0.0,3.1104,2015,2017
4450,4451,CA-2015-121965,2017-06-19,2015-06-23,Standard Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,186.690,3.0,0.0,87.7443,2015,2017
4612,4613,US-2017-165953,2016-12-31,2017-06-01,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-AR-10000588,Office Supplies,Art,Newell 345,47.616,3.0,0.2,3.5712,2017,2016
4613,4614,US-2017-165953,2016-12-31,2017-06-01,Standard Class,EP-13915,Emily Phan,Consumer,United States,Jacksonville,...,OFF-PA-10002250,Office Supplies,Paper,Things To Do Today Pad,23.480,5.0,0.2,8.2180,2017,2016
5289,5290,CA-2014-146283,2016-08-09,2014-09-15,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10002259,Office Supplies,Paper,"Geographics Note Cards, Blank, White, 8 1/2"" x...",17.904,2.0,0.2,6.2664,2014,2016
5290,5291,CA-2014-146283,2016-08-09,2014-09-15,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,966.700,5.0,0.3,-13.8100,2014,2016
5291,5292,CA-2014-146283,2016-08-09,2014-09-15,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Houston,...,OFF-PA-10000482,Office Supplies,Paper,Snap-A-Way Black Print Carbonless Ruled Speed ...,182.112,6.0,0.2,61.4628,2014,2016
5372,5373,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10003177,Office Supplies,Paper,Xerox 1999,15.552,3.0,0.2,5.4432,2015,2014
5373,5374,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,FUR-TA-10002607,Furniture,Tables,KI Conference Tables,347.361,7.0,0.3,-69.4722,2015,2014
5374,5375,CA-2015-118738,2014-10-24,2015-10-30,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,OFF-PA-10001166,Office Supplies,Paper,Xerox 2,10.368,2.0,0.2,3.6288,2015,2014
5738,5739,CA-2017-156139,2016-12-31,2017-06-01,Standard Class,BP-11155,Becky Pak,Consumer,United States,San Francisco,...,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",38.376,3.0,0.2,13.4316,2017,2016
6341,6342,US-2017-105830,2016-12-31,2017-02-01,First Class,DB-13660,Duane Benoit,Consumer,United States,Lancaster,...,OFF-ST-10002554,Office Supplies,Storage,Tennsco Industrial Shelving,156.512,4.0,0.2,-35.2152,2017,2016
6387,6388,CA-2014-134103,2017-01-30,2014-02-04,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-PA-10001204,Office Supplies,Paper,Xerox 1972,10.560,2.0,0.0,4.7520,2014,2017
6388,6389,CA-2014-134103,2017-01-30,2014-02-04,Standard Class,MV-18190,Mike Vittorini,Consumer,United States,Detroit,...,OFF-ST-10000991,Office Supplies,Storage,Space Solutions HD Industrial Steel Shelving.,229.940,2.0,0.0,6.8982,2014,2017
8586,8587,CA-2017-162015,2015-11-07,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,TEC-AC-10003832,Technology,Accessories,Logitech�P710e Mobile Speakerphone,1287.450,5.0,0.0,244.6155,2017,2015
8587,8588,CA-2017-162015,2015-11-07,2017-07-18,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,...,OFF-AP-10003040,Office Supplies,Appliances,Fellowes 8 Outlet Superior Workstation Surge P...,168.100,5.0,0.0,43.7060,2017,2015
8595,8596,CA-2014-111934,2029-05-05,2014-05-07,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-BI-10004364,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2.0,0.0,5.3460,2014,2029
8596,8597,CA-2014-111934,2029-05-05,2014-05-07,First Class,GD-14590,Giulietta Dortch,Corporate,United States,Arlington,...,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,35.440,1.0,0.0,16.6568,2014,2029
9942,9943,CA-2014-143371,2019-12-28,2015-03-01,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.820,9.0,0.0,29.9646,2014,2019
9943,9944,CA-2014-143371,2019-12-28,2015-03-01,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,OFF-SU-10002537,Office Supplies,Supplies,Acme Box Cutter Scissors,51.150,5.0,0.0,13.2990,2014,2019